### ISSUE TITLE
Use the rippl_AI.perdict to detect ripples in Monkeys

### ISSUE THREAD

**Issue by Marmotiaaa** [PridaLab/rippl-AI#2]
Hi, we are using the 5 best models to detect the ripples in head-fixed monkeys, and we use Microwire Brush Array, which is 32 microwires tightly bundled within a single Microfil tube, recording signal from pyramidal layer. We don't have any reference electrodes. In that case, we simply use 4 1*8 array as our channel map (from [0, 1, 2, 3, 4, 5, 6, 7] until [24, 25, 26, 27, 28, 29, 30, 31]). However, we find that there's a lot of noise wrongly identified as signals, just as shown in the following picture. Should we retrain the model to make them fit our data more perfectly, or we need to change our channel map? Looking forward to your reply!

( Another thing is, as it's mentioned in the README.md file, there should be a "Update" button displayed on the GUI, but we can't find it... Where can we find this "Update" button? Thanks again! )

![image](https://github.com/PridaLab/rippl-AI/assets/121848353/35885023-51fd-49c2-aa10-cb7086a76c3e)

**Comment by acnavasolive** [comment]
Hello! I am sorry I couldn't answer before, I have been out!

I don't know if you tried something else, but it makes sense that it is due to the channel map. Could you send me a examples of the LFP across all channels for a couple of visually identified SWRs? Then I can try to see what would be the best option to input into the CNN. 

Best
